[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
user=root

[program:cron]
command=cron -f
autorestart=true
stderr_logfile=/var/log/supervisor/cron-stderr.log
stdout_logfile=/var/log/supervisor/cron-stdout.log
priority=10

[program:flask]
command=python monitor_app.py
autorestart=true
stderr_logfile=/var/log/supervisor/flask-stderr.log
stdout_logfile=/var/log/supervisor/flask-stdout.log
priority=20
